apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cu4ue7736-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cu4ue7736-java-springboot-gitops